### PR TITLE
User class test_cases

### PR DESCRIPTION
**Pull request by frankip**
## What this PR will do 
* update the test cases for user class
* implement the RSVP method
# How to Test

clone the repo

 ``` git clone https://github.com/frankip/bright_events.git ```

then change the directory to the project by 

``` cd bright_events ```

* create a virtual environment run

    ``` virtualenv -p python3 venv```
* activate the environment

    ``` source venv/bin/activate```
* install requirements

``` pip install -r requirements.txt ```

* checkout to the latest branch

``` git checkout v2_events```

#run 
To test the project on your terminal run 

``` export FLASK_APP=run.py```

then

``` flask run ```

on your browser open up [http://127.0.0.1:5000/api/events](http://127.0.0.1:5000/api/events)

the endpoints
* POST /api/auth/register
* POST /api/auth/login
* POST /api/auth/logut
* POST /api/events
* GET /api/events
* PUT /api/events/<eventId>
* DELETE /api/events/<eventid>
* POST /api/events/<eventid>/rsvp
* GET /api/events/<eventid>/rsvp

# For the tests
nosetests test

### CODE REVIEW

**Comment by Rodgers-M** [comment]
Pr follows git workflow conventions with meaningful information. good method documentation.

**Comment by joewachira** [comment]
Good explanation of how to test, you could shorten it, however, to make it straight to the point.

**Comment by meshnesh** [comment]
Good implementation of test cases and programming logic

**Comment by Mwiberi** [comment]
The button with the dropdown seems not be working
Also, it's a bit heard for someone to know how to enter event data so as to POST. Otherwise, I love how you have structured the API UI

**Pull request merged**
